// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuantityMeasurementApp.Repository.Data;

#nullable disable

namespace QuantityMeasurementApp.Repository.Migrations
{
    [DbContext(typeof(QuantityDbContext))]
    partial class QuantityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuantityMeasurementApp.Model.Entities.QuantityMeasurementEntity", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("ErrorMessage").HasColumnType("text");
                    b.Property<int>("MeasurementCategory").HasColumnType("integer");
                    b.Property<string>("Operand1Unit").IsRequired().HasColumnType("text");
                    b.Property<double>("Operand1Value").HasColumnType("double precision");
                    b.Property<string>("Operand2Unit").IsRequired().HasColumnType("text");
                    b.Property<double>("Operand2Value").HasColumnType("double precision");
                    b.Property<int>("OperationType").HasColumnType("integer");
                    b.Property<string>("ResultUnit").IsRequired().HasColumnType("text");
                    b.Property<double>("ResultValue").HasColumnType("double precision");
                    b.Property<DateTime>("Timestamp").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("QuantityMeasurementApp.Model.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("PasswordHash").HasColumnType("text");
                    b.Property<string>("Role").IsRequired().HasColumnType("text");
                    b.Property<string>("Salt").HasColumnType("text");
                    b.Property<string>("Username").IsRequired().HasColumnType("text");
                    b.HasKey("Id");
                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
